name: 'Push action'
description: 'Git push'
inputs:
  message:
    description: 'Commit message'
    required: false
    default: ''
  author:
    description: 'Commit author'
    required: false
    default: '${GITHUB_ACTOR}'
  email:
    description: 'Committer email'
    required: false
    default: '${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com'
runs:
  using: 'composite'
  steps:
    - run: |
        git config --global user.name ${{ inputs.author }}
        git config --global user.email ${{ inputs.email }}
        git config pull.rebase true
        git stage -A .
        git commit -m ${{ inputs.message }}
        until git push origin ${GITHUB_REF_NAME}
        do
          git pull origin ${GITHUB_REF_NAME}
        done
      shell: bash
