name: 'Push action'
description: 'Git push'
inputs:
  message:
    description: 'Commit message'
    required: true
  author:
    description: 'Commit author'
    required: false
    default: '${GITHUB_ACTOR}'
  email:
    description: 'Committer email'
    required: false
    default: '${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com'
  rebase:
    description: 'Pull rebase config'
    required: false
    default: true
  fast-forward:
    description: 'Pull fast-forward config'
    required: false
    default: false
  branch:
    description: 'Git branch'
    required: false
    default: '${GITHUB_REF_NAME}'
  files:
    description: 'Files to push'
    required: false
    default: '.'
  allow-empty:
    description: 'Allow empty commits to be pushed'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: 'Configure the runner'
      run: |
        echo "${{ github.action_path }}" >> $GITHUB_PATH
        git config --global user.name ${{ inputs.author }}
        git config --global user.email ${{ inputs.email }}
      shell: bash
    - name: 'Set rebase pull mode'
      if: ${{ !inputs.fast-forward && inputs.rebase }}
      run: |
        git config pull.rebase true
      shell: bash
    - name: 'Set fast-forward pull mode'
      if: ${{ inputs.fast-forward }}
      run: |
        git config pull.ff true
      shell: bash
    - name: 'Commit and push the changed files'
      run: |
        setup-branch.sh ${{ inputs.branch }}
        git stage -A ${{ inputs.files }}
        commit.sh "${{ inputs.message }}" ${{ inputs.allow-empty }}
        push.sh ${{ inputs.branch }}
      shell: bash
