name: 'Push action'
description: 'Git push'
inputs:
  message:
    description: 'Commit message'
    required: false
    default: ''
  author:
    description: 'Commit author'
    required: false
    default: '${GITHUB_ACTOR}'
  email:
    description: 'Committer email'
    required: false
    default: '${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com'
  rebase:
    description: 'Pull rebase config'
    required: false
    default: true
  fast-forward:
    description: 'Pull fast-forward config'
    required: false
    default: false
  branch:
    description: 'Git branch'
    required: false
    default: '${GITHUB_REF_NAME}'
runs:
  using: 'composite'
  steps:
    - run: |
        git config --global user.name ${{ inputs.author }}
        git config --global user.email ${{ inputs.email }}
      shell: bash
    - if: ${{ !inputs.fast-forward && inputs.rebase }}
      run: |
        git config pull.rebase true
      shell: bash
    - if: ${{ inputs.fast-forward }}
      run: |
        git config pull.ff true
      shell: bash
    - run: |
        git stage -A .
        git commit -m ${{ inputs.message }}
        ./push.sh ${{ inputs.branch }}
      shell: bash
